// One-off generator for src/components/hud/istanbul-bitmap.ts.
// Downloads 36 OpenStreetMap tiles (z11) covering Istanbul, classifies each CELL×CELL block as
// water / green / urban by the OSM Carto palette, and packs the result as 2-bit base64.
// Map data © OpenStreetMap contributors (ODbL). Run: node scripts/istanbul-map.mjs
import { writeFileSync } from "node:fs";
import { PNG } from "pngjs";

const Z = 11;
const XS = [1186, 1187, 1188, 1189, 1190, 1191];
const YS = [764, 765, 766, 767, 768, 769];
const CROP = { x: 0, y: 132, w: 1536, h: 1344 }; // Black Sea coast to Marmara, Büyükçekmece to Gebze
const CELL = 12;
const WATER = [170, 211, 223];

const W = XS.length * 256;
const img = new PNG({ width: W, height: YS.length * 256 });
for (const [i, x] of XS.entries())
  for (const [j, y] of YS.entries()) {
    const res = await fetch(`https://tile.openstreetmap.org/${Z}/${x}/${y}.png`, {
      headers: { "User-Agent": "alptugildiz-site-map-build/1.0 (one-off rasterization)" },
    });
    const tile = PNG.sync.read(Buffer.from(await res.arrayBuffer()));
    for (let py = 0; py < 256; py++)
      for (let px = 0; px < 256; px++) {
        const s = (py * 256 + px) * 4;
        const d = ((j * 256 + py) * W + i * 256 + px) * 4;
        tile.data.copy(img.data, d, s, s + 4);
      }
    await new Promise((r) => setTimeout(r, 1000)); // be polite to the tile server
  }

const cols = Math.floor(CROP.w / CELL);
const rows = Math.floor(CROP.h / CELL);
const classes = new Uint8Array(cols * rows); // 0 water, 1 green, 2 urban
for (let cy = 0; cy < rows; cy++)
  for (let cx = 0; cx < cols; cx++) {
    let water = 0, green = 0, total = 0;
    for (let y = 0; y < CELL; y++)
      for (let x = 0; x < CELL; x++) {
        const p = ((CROP.y + cy * CELL + y) * W + CROP.x + cx * CELL + x) * 4;
        const [r, g, b] = img.data.subarray(p, p + 3);
        total++;
        if (Math.abs(r - WATER[0]) + Math.abs(g - WATER[1]) + Math.abs(b - WATER[2]) < 30) water++;
        else if (g > r + 18 && g > b + 18) green++;
      }
    classes[cy * cols + cx] = water > total * 0.28 ? 0 : green > (total - water) * 0.5 ? 1 : 2;
  }

const bytes = new Uint8Array(Math.ceil(classes.length / 4));
classes.forEach((c, i) => (bytes[i >> 2] |= c << ((i & 3) * 2)));

writeFileSync(
  "src/components/hud/istanbul-bitmap.ts",
  `// Generated by scripts/istanbul-map.mjs — do not edit by hand.
// Map data © OpenStreetMap contributors (ODbL). 2 bits per cell: 0 water, 1 green, 2 urban.
export const MAP_COLS = ${cols};
export const MAP_ROWS = ${rows};
export const MAP_DATA = "${Buffer.from(bytes).toString("base64")}";
`,
);
console.log(`wrote ${cols}×${rows} cells, ${bytes.length} bytes`);
